# Generated by Django 4.2 on 2023-04-26 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_participant_meetup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizeremail',
            field=models.EmailField(default='org@email.co', max_length=254),
            preserve_default=False,
        ),
    ]
